### ISSUE TITLE
Tenant cannot access her children's data.

### ISSUE THREAD

**Issue by PromptDigiserve** [digi-serve/cars_app#105]
**Describe the bug**
Tenant cannot access her children's data.

**To Reproduce**
1. Go to 'fcf.childatrisk.in.th'
2. Click on 'Login'
3. On 'main menu' and 'Children', click on each children tap, no response.

**Expected behavior**
When tenant click on children tap, she can access to these data.

![Screen Shot 2023-01-19 at 3 22 06 PM](https://user-images.githubusercontent.com/121542672/213390868-d6bc98a5-39c5-4d82-90c9-6d8fb4a76231.png)

**Comment by wongpratan** [comment]
It has a error of the `Dataview` widget in new migrate code branch.

On Production server, I rollback to use code at this commit to workaround.
https://github.com/digi-serve/ab_platform_web/commit/5a45a72fd11fe2303bd490ca365ae275e952a5a2

**Comment by PromptDigiserve** [comment]
Today (Jan, 23rd, 2023), customers still cannot access to her data.
