### ISSUE TITLE
The new info's  child  will replace  the recent child's data. ( home of the swallow )

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#22]
### Short Description

When he wanted to add the new information of the the new orphan boy / girl . After he  clicked saved this information, these new data will replace the recent data. 

### Steps to Reproduce

1. Go to '.. add  new child's info and fill in all the info .'
2. Click on '. saved...'
3 After he  clicked saved this information, these new data will replace the recent data. 
![swallolow](https://user-images.githubusercontent.com/100179546/157390915-f54f3c67-6376-439c-9425-8244001d2be5.jpg)

### Expected Behavior

after he clicked save the info. the new info should be displayed on the  screen  ( Not replacing the recent one)  ) 

### What Server are you using?

Home page of Cars 

### Screenshots

![หน้าต่าง แรก](https://user-images.githubusercontent.com/100179546/157391926-b36650b5-2452-4529-b7f1-7709dd183bf1.jpg)
**** Ps this screenshot is not the real one from HOS's  Cars account ***** .

**Comment by jamesduncan** [comment]
This might be fixed with the latest code on V2...so when we are ready to update that server I will do the work to update and then we can test again.

**Comment by jamesduncan** [comment]
Okay can we test this again to see if the issue has been resolved?
