### ISSUE TITLE
please hidden  2  children data  in EM App 

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#27]
Meen required us helped her  hidden 2 Children as following; 
![Em App 3](https://user-images.githubusercontent.com/100179546/158503818-1d6a1d09-a394-444c-b2b4-6655d02190a8.jpg)
![EM App 2](https://user-images.githubusercontent.com/100179546/158503852-dfe65053-d150-48cf-8065-bb54ffe55f3e.jpg)
thanks

**Comment by nh758** [comment]
Done
