### ISSUE TITLE
Please create the 3 User Cars 's accounts for Care Corner Orphanage. 

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#31]
the care corner staff wanted us to create  3 user  Cars's accounts. 
for director
the username might be  : Jacinth@carecorner 
for Social work
the username might be : socialwork@carcorner 
For Admin staff
the user name might be : admin@carecorner 
 
*** she asked that all the 3 users accounts  have the same login settings. thank you.

**Comment by jamesduncan** [comment]
K, can you provide us with emails for each user?
