### ISSUE TITLE
Please reduce the size of these screens  a bit.  ( carecorner.childatrisk.in.th )

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#32]
* I tested the carecorner.childatrisk.in.th . I found these screens are too big and unable to close or saved the data easily.   Would you please reduce the size of the screens as the following? 
 1.  basic Info Category  ( - admit  Info's screen  ) 
![admit info](https://user-images.githubusercontent.com/100179546/162665386-5ff2bb51-c7be-433c-b19b-9ad45b5e5bff.jpg)
2.  Medical  Category
     2.1  ( -  Prelim Psychical Detail )
![Prrlim Physicial Detail](https://user-images.githubusercontent.com/100179546/162665680-7ec2af81-5c18-4383-943c-f8bf3eaad277.jpg)
     2.2 ( Growth Log ) 
![Growth Log](https://user-images.githubusercontent.com/100179546/162665771-40dcb5ae-9e65-497c-80d2-5b1803de9994.jpg)

Thank you.

**Comment by jamesduncan** [comment]
I went through the database and udpated all popups on dev.digiserve.org that were over 500 pixels high and reduced them to 450 pixels. I have exported and updated the CARS app for Care Corner to have the new dimensions. K can you confirm you are able to edit these forms now?

**Comment by k-kay219** [comment]
Yes, I checked it. The screen had been reduced and more easy to save and close . thank you so much.
