### ISSUE TITLE
Data last updated is not showing   (  carecorner.childatrisk.in.th/)

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#33]
There are 3 points that after I filled in the data and saved, the last updated data is not shown to the screen . 

1. Basic info category 
    - Admit info  - Edit Admission info 
![admit info](https://user-images.githubusercontent.com/100179546/162874962-4287b231-f334-426a-8314-ee932742a7d9.jpg)
2. Medical Category  
    2.1 Prelim Health Exam 
    2.2 Prelim physical detail 

![medical - prelim](https://user-images.githubusercontent.com/100179546/162875169-634f864b-0ee4-4202-ab42-d5b4ca460e58.jpg)
thank you.

**Comment by jamesduncan** [comment]
For #1 it looks like the Data Collection had the default cursor unset so each time the form was submitted it created a new entry but since a cursor was never set it never showed the data. I have made the change on dev.digiserve.org and the form is working.

**Comment by jamesduncan** [comment]
The #2 is getting an error when trying to save the 'Add Physical Details' form that is required to save the 'Edit Prelim Exam' form.

"Duplicate entry '784c4d6a-afe3-4c60-854c-f7a8ce64cbfc' for key 'AB_CARS_PhysicalDetails_Prelim Exam_UNIQUE'"

**Comment by jamesduncan** [comment]
On 2.2 it seems to be working fine now other than a display bug with multi select on detail views.

**Comment by jamesduncan** [comment]
#1 is fixed on the production carecorner site as well as 2.2 is working you just have to wait until the initial data has loaded before you enter into the form.

**Comment by jamesduncan** [comment]
From what I can tell we have an issue with the "+" or "Add New" forms when the connection to the record is "one to one" and there is already a connection record created. The core issue is that the form is not showing that the connected record is already present so when you click to add a new record thinking you need to create it you are then given the error that you cannot create a new one. I will try to find out why the record is not displaying for one to one connections and hopefully that will be the only thing that needs to be fixed here. This does remind me that this could be a record where we would want to edit an existing connection but that feature may have been lost when migrating away from selectivity.

**Comment by jamesduncan** [comment]
Okay the bug in the display should be fixed with this PR.

https://github.com/digi-serve/ab_platform_web/pull/77

**Comment by jamesduncan** [comment]
There is a bigger issue here still in that you cannot edit the already existing record right now. It could be fixed with a different UI in the Interface Builder however rather than having the ability to click the edit button inside a select box.
