### ISSUE TITLE
List Children in alphabetical

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#35]
Hi, this is not urgent. there are 2 things that the staff recommended after the training. 

1.  After adding a list of children to the system, the staff wanted us to help sorting the list name of children in alphabetical order. ( Thai & English  Alphabets)
![อยากให้เรียงตามลำดับตัวอักษร](https://user-images.githubusercontent.com/100179546/164148632-3f74edfb-bc91-49e5-810c-1cc42dcfc822.jpg)

**Comment by nh758** [comment]
Separated point 2 into #37

**Comment by Achoobert** [comment]
Sorting the data collection seems to work
![image](https://user-images.githubusercontent.com/8057443/165222119-75b12940-9701-4ca7-9420-30c1365e4095.png)

![image](https://user-images.githubusercontent.com/8057443/165222372-5609b304-6938-471c-89dc-c8b8f52b45ef.png)

**Comment by Achoobert** [comment]
I have added these definitions to Care Corner. Not sure where else they need to be

**Comment by k-kay219** [comment]
> I have added these definitions to Care Corner. Not sure where else they need to be

Could you please add this change to all the faithful foundation's users as well ? thank you

**Comment by Achoobert** [comment]
Note to builder: when updating definitions
-> If adding new field
--are all labels translated?

-> make sure all roles can see app after uploading new definitions
