### ISSUE TITLE
 Please delete all these data  ( Carecorner.childatrisk.in.th )

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#36]
Please help me to delete all the red mark . It's a testing detail  that I tested the system.  Thank you. 

![ลบ 1](https://user-images.githubusercontent.com/100179546/165009442-75a4dbe2-047e-4031-8d02-97fac627e112.jpg)
![ลบ 2](https://user-images.githubusercontent.com/100179546/165009455-3e2befe5-c581-43af-ab59-3afa10d5a3a8.jpg)
![ลบ 3](https://user-images.githubusercontent.com/100179546/165009465-951e9626-d033-4c56-a9b6-1bfb3042ea78.jpg)
![ลบ 4](https://user-images.githubusercontent.com/100179546/165009476-17c68c48-5b88-4eec-b2ed-fa2f027afb65.jpg)

**Comment by nh758** [comment]
@Achoobert do you have time to look at this? If there is a way to remove staff, project, etc. from the front end, can you show K?

**Comment by Achoobert** [comment]
@k-kay219 I didn't remove the first staff record, as it is connected to a ```User```

**Comment by k-kay219** [comment]
> 
thank you for the first user, I will let the staff edit some info.
