### ISSUE TITLE
Faithful foundation  ( 5 sub - projects )

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#39]
Faithful foundation has 5 sub-projects in the foundation, 
1. Khemkhang family 
2. Foster family 
 3. Children's home 
4. Return to family 
5. University scholarships
![หลายโปรเจค](https://user-images.githubusercontent.com/100179546/167340620-7ee63bcc-61e9-43ea-8fe5-8425b7e079d2.jpg)
 I added all the 5 sub - project to " Add Projects Function " Am I right? please let me know thank you.

**Comment by Achoobert** [comment]
The purpouse of the "projects" was to be able to show only relivant children to `project workers`
Therefore a Child can only be in **one** project at a time.

If a single child cannot ever be in two projects at the same time then, yes, you set that up perfectly.
