### ISSUE TITLE
Please add customer requirements.

### ISSUE THREAD

**Issue by Deardigiserve** [digi-serve/cars_app#44]
1. CARs takes too much time to save and load about 30 seconds.
2. In Category of Relatives >> Add Relatives, Please add the label  "รายจ่ายต่อเดือน" (Expense per Month) under Salary per Month and follow by adding a text input field to enter the amount of expenses and follow by adding a file upload field for the expense's excel file or expense's PDF file. 
3. In Category of Relatives >> Add Relatives, Please add the label  "หนี้สินต่อเดือน" (Debt per Month) under Expense per Month and follow by adding a text input field to enter the amount of debts and follow by adding a file upload field for the debt's excel file or debt's PDF file. 

4. In Category of Education >> Education Info, Please add a file upload field for the education transcript under Reason for leaving. 

5. In Category of Logs >> Home visit, Please add a URL field under Map to enter the domain name of the map (Google Map).  

6. They want to change CARs from the year A.D. (Anno Domini) to B.E. (Buddhist Era) for the recording of them.

7. In Category of Education >> School Records, We can't edit and show Class Year and Year.

**Comment by nh758** [comment]
Seperated 2-5 into #45
