### ISSUE TITLE
Record and display children's data for a long time.

### ISSUE THREAD

**Issue by Deardigiserve** [digi-serve/cars_app#46]
**Is this related to a problem?**
The customer's problem is It takes a long time to record and display children's data.

**Desired Solution**
Customers want to record and display children's data faster than ever.

**Alternatives**
Is the capacity of the RAM at least 8GB? and Is the speed of the CPU at least core i3? or anything else.

**Comment by Deardigiserve** [comment]
@Achoobert record and display are faster now. I checked it and everything came back as fast as before.

**Comment by Achoobert** [comment]
> @Achoobert record and display are faster now. I checked it and everything came back as fast as before.

I am not 100% sure on this: 
But I think that the server (or at least the tenant who has new definitions) can **noticeably** slow down after updating the definitions.
The fix that I have found so far is a simple restart.

Please let us know immediately if anyone sees this again, @wongpratan may have some ideas on how to diagnose it :)

**Comment by Deardigiserve** [comment]
@Achoobert Thank you :) 
@wongpratan If I have this problem again, I will let you know immediately.
