### ISSUE TITLE
Please add a URL field under Map 

### ISSUE THREAD

**Issue by Deardigiserve** [digi-serve/cars_app#48]
## Requirements
1. In Category of Logs >> Home visit, Customers want to add a URL field under Map to fill the domain name of their map (Google Map) into CARs.

### Tasks
1.  In Category of Logs >> Home visit, Please add a URL field under Map to fill the domain name for their map.
2. Customers can fill domain name of their map in this category.

## Reference
like this picture.
![first](https://user-images.githubusercontent.com/105480132/173765224-8bbcf97e-efa7-4daa-96cc-513a22fd9683.png)

**Comment by Achoobert** [comment]
@Deardigiserve Where/when do users see this url getting clicked?

Our UI right now really mostly does add/edit, not really viewing data.

Therefore I'm guessing they will want it to be in the DOCX report?

**Comment by Deardigiserve** [comment]
It appears now and I have told prin to change the wrong thai word from "ที่อยู่เว็บไซต์ to ที่อยู่แผนที่".
![91](https://user-images.githubusercontent.com/105480132/176850946-496d429a-15b2-438e-821e-c52fbdf05830.png)

**Comment by Tacchinardi20** [comment]
OK, Already Fixed
