### ISSUE TITLE
A word in Thai is wrong

### ISSUE THREAD

**Issue by Deardigiserve** [digi-serve/cars_app#52]
**Is this related to a problem?**
A word with only wrong spelling.

**Desired Solution**
Customers only require correct spelling.

**Alternatives**
1. In Category of Education >> Education Info >> Reason for leaving, Please change a Thai word from "ย้านสถานศึกษา" to "ย้ายสถานศึกษา".

**Additional context**
![leaving](https://user-images.githubusercontent.com/105480132/173788061-70de90a3-1ebf-4596-b5d3-eab6a689a3ea.png)

**Comment by Tacchinardi20** [comment]
Already Fixed
