### ISSUE TITLE
Some small change require from Meen ( Education Matter ) 

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#57]
1. Please delete  or hide Mr. K** R** profile  from Em system. 

2. As a circle, please delete 140 $ and Monthly  pls. 

3.  Please change the figure from  161 $ to 140 $. 

4. Please change the figure from  30 $ to 15 $. 

5. As a circle,  she wanted to add more children. Some donor support more than one child.
![image](https://user-images.githubusercontent.com/10155226/179925961-0aa6ef88-300e-4bf5-bf7b-80b263174986.png)

Thank you  for your kind cooperation.

**Comment by nh758** [comment]
1-4 fixed already for.
For number 5, suggest making multiple pledges instead of one.
- Child 1 -> 70/month
- Child 2  -> 70/month

**Comment by k-kay219** [comment]
For number 5, I am still not unclear about your advise. Could you please give me more explanation ? thank you.

**Comment by nh758** [comment]
Instead of one record with 2 kids, you can make 2 records with one kid each:
![image](https://user-images.githubusercontent.com/10155226/180355970-a0a6c1b4-fc6a-4bda-9b51-deeb7f661552.png)

**Comment by k-kay219** [comment]
thank you
