### ISSUE TITLE
(Urgent !!) Customers in both faithfulheart and leadership home have problem with the save button

### ISSUE THREAD

**Issue by Deardigiserve** [digi-serve/cars_app#58]
**Is this related to a problem?**
For both customers, when they pressed the save button, there was no response at all. (All save buttons within CARs)

**Desired Solution**
Customers are able to save children's information after they press the save button.

**Comment by wongpratan** [comment]
Does it cause from childatrisk.in.th ?

I could not reproduce it.

Can you check it again ?
If it will not be working, then please you inform what the page/form that does not work.

**Comment by Deardigiserve** [comment]
@wongpratan I already checked it again and it still has the same problem on every page and every form that has the save button. This problem has been going on since last Thursday (customers informed me). I think childatrisk.in.th is not probably the cause because a couple of weeks ago the customer can still use it normally.

**Comment by wongpratan** [comment]
What is server name that have the problem ?

**Comment by Deardigiserve** [comment]
@wongpratan The system is back. Both foundations are back to normal operation. Thank you very much. ^_^
