### ISSUE TITLE
Please delete the default value (0) from the program (both Faihfulheart and Leadershiphome)

### ISSUE THREAD

**Issue by Deardigiserve** [digi-serve/cars_app#73]
**Is this related to a problem?**
The program should be fixed to be professional for presenting to customers next time.

**Desired Solution**
In Category of Medical >> Growth Log 
Customers don't want the default value (0) to appear.

**Additional context**
![3](https://user-images.githubusercontent.com/105480132/185536292-8ca4e9df-5625-4ad9-b1ca-77429c477501.png)

**Comment by Achoobert** [comment]
Proposed solution to not have empty records generated.
Have page where users go and must manually fill out fields:

![image](https://user-images.githubusercontent.com/8057443/189827652-d9416b51-c0b5-414e-92b1-be31e1c07b14.png)

Related:
https://github.com/digi-serve/ab_platform_web/pull/148
