### ISSUE TITLE
 Our customers need a search and sort and filter on the main page

### ISSUE THREAD

**Issue by Deardigiserve** [digi-serve/cars_app#99]
**Where do you experience the issue?**
Customers cannot search for children based on keywords such as age, activity, gender, education level, etc...

**Desired Solution**
Please add search, sort, and filter on the main page according to the picture.

**Alternatives**
Please add it to the red circle area.

**Additional context**
![1](https://user-images.githubusercontent.com/105480132/205031310-185e037a-bb68-4d99-be48-76f4ff89f688.png)

**Comment by nh758** [comment]
Filter and Search as it's own widget.
Tied to a datacollection. Any view using the datacollection get's updated.
Or connect other widget to a filter widget.
Clear filters.
